environments:
  - name: dev
    endpoints:
     production:
       url: 'https://jsonplaceholder.typicode.com/posts/1'

  - name: test
    endpoints:
     production:
       url: 'https://test.jsonplaceholder.typicode.com/posts/1'

  - name: production
    endpoints:
      production:
        url: 'https://prod.jsonplaceholder.typicode.com/posts/1'


